# Generated by Django 5.2.5 on 2025-09-23 02:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_events_options'),
        ('lessons', '0014_rename_teacher_id_archived_lessons_teacher'),
        ('servers', '0007_alter_archived_servers_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='lesson_id',
            new_name='lesson',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='server_id',
            new_name='server',
        ),
        migrations.CreateModel(
            name='Archived_Events',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessons')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servers.servers')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
