# Generated by Django 5.2.5 on 2025-09-23 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_lesson_id_events_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled'), ('CANCELED', 'Canceled')]),
        ),
    ]
