# Generated by Django 5.2.5 on 2025-09-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_events_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(default='PENDING', null=True),
        ),
    ]
