# Generated by Django 5.2.5 on 2025-09-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_events_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived_events',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(default='PENDING', null=True),
        ),
    ]
