# Generated by Django 5.2.5 on 2025-09-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_archived_events_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archived_events',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='event_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='archived_events',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled'), ('CANCELED', 'Canceled')], default='PENDING'),
        ),
    ]
