# Generated by Django 5.2.5 on 2025-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_archived_events_event_time_events_event_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('RESCHEDULED', 'Rescheduled'), ('CANCELED', 'Canceled')], default='PENDING'),
        ),
    ]
