# Generated by Django 5.2.5 on 2025-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_events_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_banner',
            field=models.ImageField(default='event_banner/default_event_banner.jpg', upload_to='event_banner'),
        ),
    ]
