# Generated by Django 5.2.5 on 2025-08-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
    ]
