# Generated by Django 5.2.5 on 2025-09-04 20:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherApplications',
            new_name='Teacher_Applications',
        ),
    ]
