# Generated by Django 5.2.5 on 2025-09-04 21:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_teacherapplications_teacher_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_applications',
            name='application_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='teacher_applications',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
