# Generated by Django 5.2.5 on 2025-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_applications_application_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher_applications',
            options={'verbose_name': 'Teacher Application', 'verbose_name_plural': 'Teacher Applications'},
        ),
        migrations.AlterModelOptions(
            name='teachers',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterField(
            model_name='teacher_applications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
