# Generated by Django 5.2.5 on 2025-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_alter_teacher_applications_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived_teachers',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')]),
        ),
    ]
