# Generated by Django 5.2.5 on 2025-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='server_interests',
            field=models.CharField(),
        ),
    ]
