# Generated by Django 5.2.5 on 2025-09-04 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_alter_servers_server_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Server_Application',
            new_name='Server_Applications',
        ),
    ]
