# Generated by Django 5.2.5 on 2025-09-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_rename_server_application_server_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server_applications',
            options={'verbose_name': 'Server Application', 'verbose_name_plural': 'Server Applications'},
        ),
        migrations.AlterModelOptions(
            name='servers',
            options={'verbose_name': 'Server', 'verbose_name_plural': 'Servers'},
        ),
        migrations.AddField(
            model_name='server_applications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending'),
        ),
    ]
