# Generated by Django 5.2.5 on 2025-10-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='banner',
            field=models.ImageField(blank=True, default='lesson_banner/default_banner.jpg', null=True, upload_to='lesson_banner'),
        ),
    ]
