# Generated by Django 5.2.5 on 2025-09-14 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessons_options'),
        ('teachers', '0006_alter_archived_teachers_gender_alter_teachers_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='banner',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Archived_Lessons',
            fields=[
                ('lesson_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_title', models.CharField(max_length=200)),
                ('lesson_category', models.CharField(max_length=200)),
                ('lesson_description', models.TextField()),
                ('banner', models.ImageField(blank=True, upload_to='')),
                ('is_active', models.BooleanField()),
                ('repeating', models.BooleanField()),
                ('availability', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('delete_at', models.DateTimeField(auto_now_add=True)),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teachers')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
