# Generated by Django 5.2.5 on 2025-09-16 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lessons_banner_archived_lessons'),
        ('teachers', '0006_alter_archived_teachers_gender_alter_teachers_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='availability',
        ),
        migrations.CreateModel(
            name='Teacher_Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachers')),
            ],
            options={
                'verbose_name': 'Teacher Availability',
                'verbose_name_plural': 'Teacher Availability',
                'unique_together': {('teacher', 'day', 'start_time', 'end_time')},
            },
        ),
    ]
