# Generated by Django 5.2.5 on 2025-09-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_remove_lessons_availability_teacher_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='lesson_category',
            field=models.CharField(choices=[('history', 'History'), ('psychology', 'Psychology'), ('computer science', 'Computer Science'), ('math', 'Math'), ('physics', 'Physics')]),
        ),
    ]
