# Generated by Django 5.2.5 on 2025-09-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lessons_lesson_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archived_lessons',
            name='availability',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
