# Generated by Django 5.2.5 on 2025-09-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_archived_lessons_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='repeating',
            field=models.BooleanField(default=False),
        ),
    ]
