# Generated by Django 5.2.5 on 2025-09-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_alter_lessons_repeating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='banner',
            field=models.ImageField(blank=True, upload_to='lesson_banner'),
        ),
    ]
