# Generated by Django 5.2.5 on 2025-09-23 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_lessons_banner'),
        ('teachers', '0006_alter_archived_teachers_gender_alter_teachers_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher_availability',
            name='lesson_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lessons.lessons'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lessons',
            name='repeating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Archived_Teacher_Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessons')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teachers')),
            ],
        ),
    ]
