# Generated by Django 5.2.5 on 2025-09-23 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_teacher_availability_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archived_lessons',
            name='repeating',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
