# Generated by Django 5.2.5 on 2025-09-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_archived_lessons_repeating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher_availability',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
