# Generated by Django 5.2.5 on 2025-09-23 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_rename_lesson_id_teacher_availability_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archived_teacher_availability',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
