# Generated by Django 5.2.5 on 2025-09-23 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_rename_lesson_id_archived_teacher_availability_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
