# Generated by Django 5.2.5 on 2025-09-23 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0013_rename_teacher_id_lessons_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archived_lessons',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
