# Generated by Django 5.2.5 on 2025-09-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_rename_teacher_id_archived_lessons_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='banner',
            field=models.ImageField(blank=True, default='lesson_banner/default_banner.jpg', upload_to='lesson_banner'),
        ),
    ]
